CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'user',
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS players (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  sport VARCHAR(100) NOT NULL,
  position VARCHAR(100) NOT NULL,
  age INTEGER NOT NULL CHECK (age BETWEEN 1 AND 120),
  team VARCHAR(150) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);